---
title: "Rep_Data_PeerAssessment1"
author: "sumanth khadke"
date: '2022-06-22'
output: html_document
---


```{r,echo=TRUE}
full_data <- read.csv("activity.csv", header = TRUE)
main_data <- na.omit(full_data)

steps_each_day <- aggregate(steps ~ date, full_data, sum)
hist(steps_each_day$steps, breaks = 20,
     main = paste("Total Number of Steps Taken Each Day")
     , xlab = "Number of Steps", col = "blue")
```
```{r,echo=TRUE}     
mean_steps <- mean(steps_each_day$steps)
median_steps <- median(steps_each_day$steps)

sprintf("Mean of the steps taken each day %.3f", mean_steps)

sprintf("Median of the steps taken each day %.3f", median_steps)
```

```{r,echo=TRUE}
avg_steps_across_all_days <- aggregate(steps ~ interval, full_data, mean)
plot(avg_steps_across_all_days$interval, avg_steps_across_all_days$steps, type = "l", xlab = "Interval"
        , ylab = "Average Steps", main = "Average Number of Steps per Day by Interval")
```
```{r,echo=TRUE}
max_step_interval <- avg_steps_across_all_days[which.max(avg_steps_across_all_days$steps),1]
sprintf("Maximum number of steps were taken in interval %d", max_step_interval)
```
```{r,echo=TRUE}
sprintf("Total number of rows with missing values is %d", sum(is.na(full_data)))
```

```{r,echo=TRUE}
library(lattice)
library(ggplot2)
library(Formula)
library(survival)
library(Hmisc)
full_data_imputed <- full_data
full_data_imputed$weekday <- weekdays(as.Date(full_data$date))


full_data_imputed$steps <- ave(full_data$steps, full_data_imputed$weekday,FUN=function(x) ifelse(is.na(x), mean(x,na.rm=TRUE),x))

steps_each_day_imputed <- aggregate(steps ~ date, full_data_imputed, sum)

hist(steps_each_day_imputed$steps, breaks = 20, col = 'blue' ,main = paste("Total Number of Steps Taken Each Day"), xlab = "Number of Steps", ylim = c(0,20))
hist(steps_each_day$steps, breaks = 20, col = 'red', main = paste("Total Number of Steps Taken Each Day"), xlab = "Number of Steps", add=T)
legend("topright", c("Imputed", "Non-imputed"), col=c("black", "red"),lwd = 10)

```
```{r,echo=TRUE}
mean_steps_imputed <- mean(steps_each_day_imputed$steps)
median_steps_imputed <- median(steps_each_day_imputed$steps)

```
```{r,echo=TRUE}
comparison_table <- matrix(c(mean_steps, mean_steps_imputed, median_steps, median_steps_imputed), ncol = 2, byrow = TRUE)

colnames(comparison_table) <- c("Original", "Imputed")
rownames(comparison_table) <- c("mean", "median")
```
```{r,echo=TRUE}
full_data_imputed$weekend_factor <- ifelse(weekdays(as.Date(full_data_imputed$date)) %in% c("Saturday", "Sunday"), "weekend", "weekday")

panel_plot <- aggregate(steps ~ interval + weekend_factor, data = full_data_imputed, mean)

library(ggplot2)
ggplot(panel_plot, aes(interval, steps)) + geom_line() + facet_grid(weekend_factor ~ .) + xlab("Interval") + ylab("Average Steps") + ggtitle("Weekdays vs. Weekends Average Steps Pattern") + theme(plot.title = element_text(hjust = 0.5))
```
        